version: 2

project_name: credstack

before:
  hooks:
    - go mod tidy

builds:
  - id: "credstack-api"
    main: "./cmd/api"
    binary: credstack-api
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -v
    ldflags:
      - '-s -w'
    env:
      - CGO_ENABLED=0

source:
  enabled: true
  name_template: "{{ .ProjectName }}_source"
  format: 'tar.gz'
  files:
    - "**/*.go"
    - "**/*.md"
    - "*.md"
    - "go.mod"
    - "go.sum"
    - "Dockerfile"
    - "LICENSE"

archives:
  - id: binaries
    format: 'binary'
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^build:"
      - "^style:"

release:
  footer: >-
    ---

    This is a beta release. Use at your own risk.\n
