version: 2

project_name: credstack

before:
  hooks:
    - go mod tidy

builds:
  - id: "credstack-api"
    main: "./cmd/api"
    binary: credstack-api
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -v
    ldflags:
      - '-s -w'
    env:
      - CGO_ENABLED=0

archives:
  - id: source
    formats: ["zip", "tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}"
    files:
      - "**/*.go"
      - "**/*.md"
      - "*.md"
      - go.mod
      - go.sum
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^build:"
      - "^style:"

release:
  footer: >-
    ---

    This is a beta release. Use at your own risk.\n
    Release provides the library only and does not provide the API or the CLI.\n
    \nReleased by [GoReleaser](https://github.com/goreleaser/goreleaser).
