version: 2

project_name: credstackctl

before:
  hooks:
    - go mod tidy

builds:
  - id: "cli"
    main: "main.go"
    binary: credstackctl
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -v
    ldflags:
      - '-s -w'
    env:
      - CGO_ENABLED=0

source:
  enabled: true
  name_template: "{{ .ProjectName }}-{{ .Version }}_source"
  format: 'tar.gz'

archives:
  - id: binaries
    formats: ['binary']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^build:"
      - "^style:"

release:
  footer: >-
    ---

    This is a beta release. Use at your own risk.\n
