apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: credstack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: credstack
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu # ideally this would eventually scale based on request count
        target:
          type: Utilization
          averageUtilization: 75
