name: Build
run-name: "credstack-api: Build ${{github.ref_name}}"

on:
  push:
    branches-ignore:
      - "ci/**" # always ignore branches that contain only changes to releases/CI-CD
      - "docs/**"
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate with Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: credstack/credstack-api:latest,credstack/credstack-api:${{github.ref_name}}